# File mẫu 4: Dành cho dự án Native Android (Kotlin / Java)
# Đường dẫn tạo trong project con: <repo-app>/.github/workflows/ci.yml

name: Native Android CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  android-ci:
    uses: gk182/ci-templates/.github/workflows/mobile-ci.yml@main
    with:
      project_type: android
      build_ios: false
      run_deploy: ${{ github.ref == 'refs/heads/main' }}
      deploy_target: play_internal # play_internal | firebase | none
    secrets: inherit
